// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/service.proto

package service

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Category struct {
	Name                 string      `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	ID                   int32       `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
	ParentCategories     []*Category `protobuf:"bytes,3,rep,name=ParentCategories,proto3" json:"ParentCategories,omitempty"`
	ImagePaths           []string    `protobuf:"bytes,4,rep,name=ImagePaths,proto3" json:"ImagePaths,omitempty"`
	Products             []*Product  `protobuf:"bytes,5,rep,name=Products,proto3" json:"Products,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Category) Reset()         { *m = Category{} }
func (m *Category) String() string { return proto.CompactTextString(m) }
func (*Category) ProtoMessage()    {}
func (*Category) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{0}
}

func (m *Category) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Category.Unmarshal(m, b)
}
func (m *Category) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Category.Marshal(b, m, deterministic)
}
func (m *Category) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Category.Merge(m, src)
}
func (m *Category) XXX_Size() int {
	return xxx_messageInfo_Category.Size(m)
}
func (m *Category) XXX_DiscardUnknown() {
	xxx_messageInfo_Category.DiscardUnknown(m)
}

var xxx_messageInfo_Category proto.InternalMessageInfo

func (m *Category) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Category) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Category) GetParentCategories() []*Category {
	if m != nil {
		return m.ParentCategories
	}
	return nil
}

func (m *Category) GetImagePaths() []string {
	if m != nil {
		return m.ImagePaths
	}
	return nil
}

func (m *Category) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

type VariantProduct struct {
	Name                 string    `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Category             *Category `protobuf:"bytes,2,opt,name=Category,proto3" json:"Category,omitempty"`
	ID                   int32     `protobuf:"varint,3,opt,name=ID,proto3" json:"ID,omitempty"`
	ImagePaths           []string  `protobuf:"bytes,4,rep,name=ImagePaths,proto3" json:"ImagePaths,omitempty"`
	UnitPrice            int32     `protobuf:"varint,5,opt,name=UnitPrice,proto3" json:"UnitPrice,omitempty"`
	MRP                  int32     `protobuf:"varint,6,opt,name=MRP,proto3" json:"MRP,omitempty"`
	Cashback             int32     `protobuf:"varint,7,opt,name=Cashback,proto3" json:"Cashback,omitempty"`
	Unit                 string    `protobuf:"bytes,8,opt,name=Unit,proto3" json:"Unit,omitempty"`
	MemberPrice          int32     `protobuf:"varint,9,opt,name=MemberPrice,proto3" json:"MemberPrice,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *VariantProduct) Reset()         { *m = VariantProduct{} }
func (m *VariantProduct) String() string { return proto.CompactTextString(m) }
func (*VariantProduct) ProtoMessage()    {}
func (*VariantProduct) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{1}
}

func (m *VariantProduct) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VariantProduct.Unmarshal(m, b)
}
func (m *VariantProduct) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VariantProduct.Marshal(b, m, deterministic)
}
func (m *VariantProduct) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VariantProduct.Merge(m, src)
}
func (m *VariantProduct) XXX_Size() int {
	return xxx_messageInfo_VariantProduct.Size(m)
}
func (m *VariantProduct) XXX_DiscardUnknown() {
	xxx_messageInfo_VariantProduct.DiscardUnknown(m)
}

var xxx_messageInfo_VariantProduct proto.InternalMessageInfo

func (m *VariantProduct) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VariantProduct) GetCategory() *Category {
	if m != nil {
		return m.Category
	}
	return nil
}

func (m *VariantProduct) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *VariantProduct) GetImagePaths() []string {
	if m != nil {
		return m.ImagePaths
	}
	return nil
}

func (m *VariantProduct) GetUnitPrice() int32 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

func (m *VariantProduct) GetMRP() int32 {
	if m != nil {
		return m.MRP
	}
	return 0
}

func (m *VariantProduct) GetCashback() int32 {
	if m != nil {
		return m.Cashback
	}
	return 0
}

func (m *VariantProduct) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

func (m *VariantProduct) GetMemberPrice() int32 {
	if m != nil {
		return m.MemberPrice
	}
	return 0
}

type Product struct {
	Name                 string            `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Variants             []*VariantProduct `protobuf:"bytes,2,rep,name=Variants,proto3" json:"Variants,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Product) Reset()         { *m = Product{} }
func (m *Product) String() string { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()    {}
func (*Product) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{2}
}

func (m *Product) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Product.Unmarshal(m, b)
}
func (m *Product) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Product.Marshal(b, m, deterministic)
}
func (m *Product) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Product.Merge(m, src)
}
func (m *Product) XXX_Size() int {
	return xxx_messageInfo_Product.Size(m)
}
func (m *Product) XXX_DiscardUnknown() {
	xxx_messageInfo_Product.DiscardUnknown(m)
}

var xxx_messageInfo_Product proto.InternalMessageInfo

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetVariants() []*VariantProduct {
	if m != nil {
		return m.Variants
	}
	return nil
}

type Cart struct {
	Products             []*VariantProduct `protobuf:"bytes,1,rep,name=Products,proto3" json:"Products,omitempty"`
	Quantities           []int32           `protobuf:"varint,2,rep,packed,name=Quantities,proto3" json:"Quantities,omitempty"`
	Comments             []string          `protobuf:"bytes,3,rep,name=Comments,proto3" json:"Comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Cart) Reset()         { *m = Cart{} }
func (m *Cart) String() string { return proto.CompactTextString(m) }
func (*Cart) ProtoMessage()    {}
func (*Cart) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{3}
}

func (m *Cart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cart.Unmarshal(m, b)
}
func (m *Cart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cart.Marshal(b, m, deterministic)
}
func (m *Cart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cart.Merge(m, src)
}
func (m *Cart) XXX_Size() int {
	return xxx_messageInfo_Cart.Size(m)
}
func (m *Cart) XXX_DiscardUnknown() {
	xxx_messageInfo_Cart.DiscardUnknown(m)
}

var xxx_messageInfo_Cart proto.InternalMessageInfo

func (m *Cart) GetProducts() []*VariantProduct {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *Cart) GetQuantities() []int32 {
	if m != nil {
		return m.Quantities
	}
	return nil
}

func (m *Cart) GetComments() []string {
	if m != nil {
		return m.Comments
	}
	return nil
}

type Order struct {
	Cart             *Cart  `protobuf:"bytes,1,opt,name=Cart,proto3" json:"Cart,omitempty"`
	FinalComment     string `protobuf:"bytes,2,opt,name=FinalComment,proto3" json:"FinalComment,omitempty"`
	DeliveryTimeUnix int64  `protobuf:"varint,3,opt,name=DeliveryTimeUnix,proto3" json:"DeliveryTimeUnix,omitempty"`
	//   string PaymentMode = 4;
	UserDetails          *User    `protobuf:"bytes,5,opt,name=UserDetails,proto3" json:"UserDetails,omitempty"`
	Total                int32    `protobuf:"varint,6,opt,name=Total,proto3" json:"Total,omitempty"`
	Shipping             int32    `protobuf:"varint,7,opt,name=Shipping,proto3" json:"Shipping,omitempty"`
	GrandTotal           int32    `protobuf:"varint,8,opt,name=GrandTotal,proto3" json:"GrandTotal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{4}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetCart() *Cart {
	if m != nil {
		return m.Cart
	}
	return nil
}

func (m *Order) GetFinalComment() string {
	if m != nil {
		return m.FinalComment
	}
	return ""
}

func (m *Order) GetDeliveryTimeUnix() int64 {
	if m != nil {
		return m.DeliveryTimeUnix
	}
	return 0
}

func (m *Order) GetUserDetails() *User {
	if m != nil {
		return m.UserDetails
	}
	return nil
}

func (m *Order) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Order) GetShipping() int32 {
	if m != nil {
		return m.Shipping
	}
	return 0
}

func (m *Order) GetGrandTotal() int32 {
	if m != nil {
		return m.GrandTotal
	}
	return 0
}

type LoginDetails struct {
	TimeUnix             int64    `protobuf:"varint,1,opt,name=TimeUnix,proto3" json:"TimeUnix,omitempty"`
	IP                   string   `protobuf:"bytes,2,opt,name=IP,proto3" json:"IP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginDetails) Reset()         { *m = LoginDetails{} }
func (m *LoginDetails) String() string { return proto.CompactTextString(m) }
func (*LoginDetails) ProtoMessage()    {}
func (*LoginDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{5}
}

func (m *LoginDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginDetails.Unmarshal(m, b)
}
func (m *LoginDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginDetails.Marshal(b, m, deterministic)
}
func (m *LoginDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginDetails.Merge(m, src)
}
func (m *LoginDetails) XXX_Size() int {
	return xxx_messageInfo_LoginDetails.Size(m)
}
func (m *LoginDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginDetails.DiscardUnknown(m)
}

var xxx_messageInfo_LoginDetails proto.InternalMessageInfo

func (m *LoginDetails) GetTimeUnix() int64 {
	if m != nil {
		return m.TimeUnix
	}
	return 0
}

func (m *LoginDetails) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

type User struct {
	FirstName            string          `protobuf:"bytes,1,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string          `protobuf:"bytes,2,opt,name=LastName,proto3" json:"LastName,omitempty"`
	Phone                int64           `protobuf:"varint,3,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Email                string          `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
	Address1             string          `protobuf:"bytes,5,opt,name=Address1,proto3" json:"Address1,omitempty"`
	Address2             string          `protobuf:"bytes,6,opt,name=Address2,proto3" json:"Address2,omitempty"`
	City                 string          `protobuf:"bytes,7,opt,name=City,proto3" json:"City,omitempty"`
	State                string          `protobuf:"bytes,8,opt,name=State,proto3" json:"State,omitempty"`
	Country              string          `protobuf:"bytes,9,opt,name=Country,proto3" json:"Country,omitempty"`
	Pincode              int64           `protobuf:"varint,10,opt,name=Pincode,proto3" json:"Pincode,omitempty"`
	Cart                 *Cart           `protobuf:"bytes,11,opt,name=Cart,proto3" json:"Cart,omitempty"`
	Funds                int32           `protobuf:"varint,12,opt,name=Funds,proto3" json:"Funds,omitempty"`
	Member               bool            `protobuf:"varint,13,opt,name=Member,proto3" json:"Member,omitempty"`
	LoginDetails         []*LoginDetails `protobuf:"bytes,14,rep,name=LoginDetails,proto3" json:"LoginDetails,omitempty"`
	Password             string          `protobuf:"bytes,15,opt,name=Password,proto3" json:"Password,omitempty"`
	Orders               []*SuccessOrder `protobuf:"bytes,16,rep,name=Orders,proto3" json:"Orders,omitempty"`
	ID                   string          `protobuf:"bytes,17,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{6}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetPhone() int64 {
	if m != nil {
		return m.Phone
	}
	return 0
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetAddress1() string {
	if m != nil {
		return m.Address1
	}
	return ""
}

func (m *User) GetAddress2() string {
	if m != nil {
		return m.Address2
	}
	return ""
}

func (m *User) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *User) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *User) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *User) GetPincode() int64 {
	if m != nil {
		return m.Pincode
	}
	return 0
}

func (m *User) GetCart() *Cart {
	if m != nil {
		return m.Cart
	}
	return nil
}

func (m *User) GetFunds() int32 {
	if m != nil {
		return m.Funds
	}
	return 0
}

func (m *User) GetMember() bool {
	if m != nil {
		return m.Member
	}
	return false
}

func (m *User) GetLoginDetails() []*LoginDetails {
	if m != nil {
		return m.LoginDetails
	}
	return nil
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetOrders() []*SuccessOrder {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *User) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type SignupRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupRequest) Reset()         { *m = SignupRequest{} }
func (m *SignupRequest) String() string { return proto.CompactTextString(m) }
func (*SignupRequest) ProtoMessage()    {}
func (*SignupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{7}
}

func (m *SignupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupRequest.Unmarshal(m, b)
}
func (m *SignupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupRequest.Marshal(b, m, deterministic)
}
func (m *SignupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupRequest.Merge(m, src)
}
func (m *SignupRequest) XXX_Size() int {
	return xxx_messageInfo_SignupRequest.Size(m)
}
func (m *SignupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SignupRequest proto.InternalMessageInfo

func (m *SignupRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type SignupResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignupResponse) Reset()         { *m = SignupResponse{} }
func (m *SignupResponse) String() string { return proto.CompactTextString(m) }
func (*SignupResponse) ProtoMessage()    {}
func (*SignupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{8}
}

func (m *SignupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignupResponse.Unmarshal(m, b)
}
func (m *SignupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignupResponse.Marshal(b, m, deterministic)
}
func (m *SignupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignupResponse.Merge(m, src)
}
func (m *SignupResponse) XXX_Size() int {
	return xxx_messageInfo_SignupResponse.Size(m)
}
func (m *SignupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SignupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SignupResponse proto.InternalMessageInfo

func (m *SignupResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *SignupResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type LoginRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	ToKeepLoggedIn       bool     `protobuf:"varint,3,opt,name=ToKeepLoggedIn,proto3" json:"ToKeepLoggedIn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{9}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetToKeepLoggedIn() bool {
	if m != nil {
		return m.ToKeepLoggedIn
	}
	return false
}

type LoginResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{10}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type LogoutRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{11}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type LogoutResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutResponse) Reset()         { *m = LogoutResponse{} }
func (m *LogoutResponse) String() string { return proto.CompactTextString(m) }
func (*LogoutResponse) ProtoMessage()    {}
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{12}
}

func (m *LogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutResponse.Unmarshal(m, b)
}
func (m *LogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutResponse.Marshal(b, m, deterministic)
}
func (m *LogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutResponse.Merge(m, src)
}
func (m *LogoutResponse) XXX_Size() int {
	return xxx_messageInfo_LogoutResponse.Size(m)
}
func (m *LogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutResponse proto.InternalMessageInfo

func (m *LogoutResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type AddToCartRequest struct {
	Product              *VariantProduct `protobuf:"bytes,1,opt,name=Product,proto3" json:"Product,omitempty"`
	Quantity             int32           `protobuf:"varint,2,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Comments             string          `protobuf:"bytes,3,opt,name=Comments,proto3" json:"Comments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *AddToCartRequest) Reset()         { *m = AddToCartRequest{} }
func (m *AddToCartRequest) String() string { return proto.CompactTextString(m) }
func (*AddToCartRequest) ProtoMessage()    {}
func (*AddToCartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{13}
}

func (m *AddToCartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToCartRequest.Unmarshal(m, b)
}
func (m *AddToCartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToCartRequest.Marshal(b, m, deterministic)
}
func (m *AddToCartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToCartRequest.Merge(m, src)
}
func (m *AddToCartRequest) XXX_Size() int {
	return xxx_messageInfo_AddToCartRequest.Size(m)
}
func (m *AddToCartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToCartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddToCartRequest proto.InternalMessageInfo

func (m *AddToCartRequest) GetProduct() *VariantProduct {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *AddToCartRequest) GetQuantity() int32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

func (m *AddToCartRequest) GetComments() string {
	if m != nil {
		return m.Comments
	}
	return ""
}

type AddToCartResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddToCartResponse) Reset()         { *m = AddToCartResponse{} }
func (m *AddToCartResponse) String() string { return proto.CompactTextString(m) }
func (*AddToCartResponse) ProtoMessage()    {}
func (*AddToCartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{14}
}

func (m *AddToCartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddToCartResponse.Unmarshal(m, b)
}
func (m *AddToCartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddToCartResponse.Marshal(b, m, deterministic)
}
func (m *AddToCartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddToCartResponse.Merge(m, src)
}
func (m *AddToCartResponse) XXX_Size() int {
	return xxx_messageInfo_AddToCartResponse.Size(m)
}
func (m *AddToCartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddToCartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddToCartResponse proto.InternalMessageInfo

func (m *AddToCartResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type ReadCartRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadCartRequest) Reset()         { *m = ReadCartRequest{} }
func (m *ReadCartRequest) String() string { return proto.CompactTextString(m) }
func (*ReadCartRequest) ProtoMessage()    {}
func (*ReadCartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{15}
}

func (m *ReadCartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadCartRequest.Unmarshal(m, b)
}
func (m *ReadCartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadCartRequest.Marshal(b, m, deterministic)
}
func (m *ReadCartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadCartRequest.Merge(m, src)
}
func (m *ReadCartRequest) XXX_Size() int {
	return xxx_messageInfo_ReadCartRequest.Size(m)
}
func (m *ReadCartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadCartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadCartRequest proto.InternalMessageInfo

type ReadCartResponse struct {
	Cart                 *Cart    `protobuf:"bytes,1,opt,name=Cart,proto3" json:"Cart,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadCartResponse) Reset()         { *m = ReadCartResponse{} }
func (m *ReadCartResponse) String() string { return proto.CompactTextString(m) }
func (*ReadCartResponse) ProtoMessage()    {}
func (*ReadCartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{16}
}

func (m *ReadCartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadCartResponse.Unmarshal(m, b)
}
func (m *ReadCartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadCartResponse.Marshal(b, m, deterministic)
}
func (m *ReadCartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadCartResponse.Merge(m, src)
}
func (m *ReadCartResponse) XXX_Size() int {
	return xxx_messageInfo_ReadCartResponse.Size(m)
}
func (m *ReadCartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadCartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadCartResponse proto.InternalMessageInfo

func (m *ReadCartResponse) GetCart() *Cart {
	if m != nil {
		return m.Cart
	}
	return nil
}

type UpdateCartRequest struct {
	Cart                 *Cart    `protobuf:"bytes,1,opt,name=Cart,proto3" json:"Cart,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCartRequest) Reset()         { *m = UpdateCartRequest{} }
func (m *UpdateCartRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateCartRequest) ProtoMessage()    {}
func (*UpdateCartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{17}
}

func (m *UpdateCartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCartRequest.Unmarshal(m, b)
}
func (m *UpdateCartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCartRequest.Marshal(b, m, deterministic)
}
func (m *UpdateCartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCartRequest.Merge(m, src)
}
func (m *UpdateCartRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateCartRequest.Size(m)
}
func (m *UpdateCartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCartRequest proto.InternalMessageInfo

func (m *UpdateCartRequest) GetCart() *Cart {
	if m != nil {
		return m.Cart
	}
	return nil
}

type UpdateCartResponse struct {
	Cart                 *Cart    `protobuf:"bytes,2,opt,name=Cart,proto3" json:"Cart,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateCartResponse) Reset()         { *m = UpdateCartResponse{} }
func (m *UpdateCartResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateCartResponse) ProtoMessage()    {}
func (*UpdateCartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{18}
}

func (m *UpdateCartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateCartResponse.Unmarshal(m, b)
}
func (m *UpdateCartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateCartResponse.Marshal(b, m, deterministic)
}
func (m *UpdateCartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateCartResponse.Merge(m, src)
}
func (m *UpdateCartResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateCartResponse.Size(m)
}
func (m *UpdateCartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateCartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateCartResponse proto.InternalMessageInfo

func (m *UpdateCartResponse) GetCart() *Cart {
	if m != nil {
		return m.Cart
	}
	return nil
}

type EmptyCartRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyCartRequest) Reset()         { *m = EmptyCartRequest{} }
func (m *EmptyCartRequest) String() string { return proto.CompactTextString(m) }
func (*EmptyCartRequest) ProtoMessage()    {}
func (*EmptyCartRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{19}
}

func (m *EmptyCartRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyCartRequest.Unmarshal(m, b)
}
func (m *EmptyCartRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyCartRequest.Marshal(b, m, deterministic)
}
func (m *EmptyCartRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyCartRequest.Merge(m, src)
}
func (m *EmptyCartRequest) XXX_Size() int {
	return xxx_messageInfo_EmptyCartRequest.Size(m)
}
func (m *EmptyCartRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyCartRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyCartRequest proto.InternalMessageInfo

type EmptyCartResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyCartResponse) Reset()         { *m = EmptyCartResponse{} }
func (m *EmptyCartResponse) String() string { return proto.CompactTextString(m) }
func (*EmptyCartResponse) ProtoMessage()    {}
func (*EmptyCartResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{20}
}

func (m *EmptyCartResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyCartResponse.Unmarshal(m, b)
}
func (m *EmptyCartResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyCartResponse.Marshal(b, m, deterministic)
}
func (m *EmptyCartResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyCartResponse.Merge(m, src)
}
func (m *EmptyCartResponse) XXX_Size() int {
	return xxx_messageInfo_EmptyCartResponse.Size(m)
}
func (m *EmptyCartResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyCartResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyCartResponse proto.InternalMessageInfo

func (m *EmptyCartResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type CheckoutRequest struct {
	Cart                 *Cart    `protobuf:"bytes,1,opt,name=Cart,proto3" json:"Cart,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckoutRequest) Reset()         { *m = CheckoutRequest{} }
func (m *CheckoutRequest) String() string { return proto.CompactTextString(m) }
func (*CheckoutRequest) ProtoMessage()    {}
func (*CheckoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{21}
}

func (m *CheckoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckoutRequest.Unmarshal(m, b)
}
func (m *CheckoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckoutRequest.Marshal(b, m, deterministic)
}
func (m *CheckoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckoutRequest.Merge(m, src)
}
func (m *CheckoutRequest) XXX_Size() int {
	return xxx_messageInfo_CheckoutRequest.Size(m)
}
func (m *CheckoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckoutRequest proto.InternalMessageInfo

func (m *CheckoutRequest) GetCart() *Cart {
	if m != nil {
		return m.Cart
	}
	return nil
}

type CheckoutResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=Order,proto3" json:"Order,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckoutResponse) Reset()         { *m = CheckoutResponse{} }
func (m *CheckoutResponse) String() string { return proto.CompactTextString(m) }
func (*CheckoutResponse) ProtoMessage()    {}
func (*CheckoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{22}
}

func (m *CheckoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckoutResponse.Unmarshal(m, b)
}
func (m *CheckoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckoutResponse.Marshal(b, m, deterministic)
}
func (m *CheckoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckoutResponse.Merge(m, src)
}
func (m *CheckoutResponse) XXX_Size() int {
	return xxx_messageInfo_CheckoutResponse.Size(m)
}
func (m *CheckoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckoutResponse proto.InternalMessageInfo

func (m *CheckoutResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *CheckoutResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type EditUserRequest struct {
	UserBefore           *User    `protobuf:"bytes,1,opt,name=UserBefore,proto3" json:"UserBefore,omitempty"`
	UserAfter            *User    `protobuf:"bytes,2,opt,name=UserAfter,proto3" json:"UserAfter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditUserRequest) Reset()         { *m = EditUserRequest{} }
func (m *EditUserRequest) String() string { return proto.CompactTextString(m) }
func (*EditUserRequest) ProtoMessage()    {}
func (*EditUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{23}
}

func (m *EditUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditUserRequest.Unmarshal(m, b)
}
func (m *EditUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditUserRequest.Marshal(b, m, deterministic)
}
func (m *EditUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditUserRequest.Merge(m, src)
}
func (m *EditUserRequest) XXX_Size() int {
	return xxx_messageInfo_EditUserRequest.Size(m)
}
func (m *EditUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditUserRequest proto.InternalMessageInfo

func (m *EditUserRequest) GetUserBefore() *User {
	if m != nil {
		return m.UserBefore
	}
	return nil
}

func (m *EditUserRequest) GetUserAfter() *User {
	if m != nil {
		return m.UserAfter
	}
	return nil
}

type EditUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	Success              bool     `protobuf:"varint,2,opt,name=Success,proto3" json:"Success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditUserResponse) Reset()         { *m = EditUserResponse{} }
func (m *EditUserResponse) String() string { return proto.CompactTextString(m) }
func (*EditUserResponse) ProtoMessage()    {}
func (*EditUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{24}
}

func (m *EditUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditUserResponse.Unmarshal(m, b)
}
func (m *EditUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditUserResponse.Marshal(b, m, deterministic)
}
func (m *EditUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditUserResponse.Merge(m, src)
}
func (m *EditUserResponse) XXX_Size() int {
	return xxx_messageInfo_EditUserResponse.Size(m)
}
func (m *EditUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditUserResponse proto.InternalMessageInfo

func (m *EditUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *EditUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type PayRequest struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=Order,proto3" json:"Order,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PayRequest) Reset()         { *m = PayRequest{} }
func (m *PayRequest) String() string { return proto.CompactTextString(m) }
func (*PayRequest) ProtoMessage()    {}
func (*PayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{25}
}

func (m *PayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayRequest.Unmarshal(m, b)
}
func (m *PayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayRequest.Marshal(b, m, deterministic)
}
func (m *PayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayRequest.Merge(m, src)
}
func (m *PayRequest) XXX_Size() int {
	return xxx_messageInfo_PayRequest.Size(m)
}
func (m *PayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PayRequest proto.InternalMessageInfo

func (m *PayRequest) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

type SuccessOrder struct {
	Cart                 *Cart    `protobuf:"bytes,1,opt,name=Cart,proto3" json:"Cart,omitempty"`
	FinalComment         string   `protobuf:"bytes,2,opt,name=FinalComment,proto3" json:"FinalComment,omitempty"`
	DeliveryTimeUnix     int64    `protobuf:"varint,3,opt,name=DeliveryTimeUnix,proto3" json:"DeliveryTimeUnix,omitempty"`
	PaymentMode          string   `protobuf:"bytes,4,opt,name=PaymentMode,proto3" json:"PaymentMode,omitempty"`
	UserDetails          *User    `protobuf:"bytes,5,opt,name=UserDetails,proto3" json:"UserDetails,omitempty"`
	Total                int32    `protobuf:"varint,6,opt,name=Total,proto3" json:"Total,omitempty"`
	Shipping             int32    `protobuf:"varint,7,opt,name=Shipping,proto3" json:"Shipping,omitempty"`
	GrandTotal           int32    `protobuf:"varint,8,opt,name=GrandTotal,proto3" json:"GrandTotal,omitempty"`
	Progress             string   `protobuf:"bytes,9,opt,name=Progress,proto3" json:"Progress,omitempty"`
	TrackDetails         string   `protobuf:"bytes,10,opt,name=TrackDetails,proto3" json:"TrackDetails,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SuccessOrder) Reset()         { *m = SuccessOrder{} }
func (m *SuccessOrder) String() string { return proto.CompactTextString(m) }
func (*SuccessOrder) ProtoMessage()    {}
func (*SuccessOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{26}
}

func (m *SuccessOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SuccessOrder.Unmarshal(m, b)
}
func (m *SuccessOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SuccessOrder.Marshal(b, m, deterministic)
}
func (m *SuccessOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SuccessOrder.Merge(m, src)
}
func (m *SuccessOrder) XXX_Size() int {
	return xxx_messageInfo_SuccessOrder.Size(m)
}
func (m *SuccessOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_SuccessOrder.DiscardUnknown(m)
}

var xxx_messageInfo_SuccessOrder proto.InternalMessageInfo

func (m *SuccessOrder) GetCart() *Cart {
	if m != nil {
		return m.Cart
	}
	return nil
}

func (m *SuccessOrder) GetFinalComment() string {
	if m != nil {
		return m.FinalComment
	}
	return ""
}

func (m *SuccessOrder) GetDeliveryTimeUnix() int64 {
	if m != nil {
		return m.DeliveryTimeUnix
	}
	return 0
}

func (m *SuccessOrder) GetPaymentMode() string {
	if m != nil {
		return m.PaymentMode
	}
	return ""
}

func (m *SuccessOrder) GetUserDetails() *User {
	if m != nil {
		return m.UserDetails
	}
	return nil
}

func (m *SuccessOrder) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *SuccessOrder) GetShipping() int32 {
	if m != nil {
		return m.Shipping
	}
	return 0
}

func (m *SuccessOrder) GetGrandTotal() int32 {
	if m != nil {
		return m.GrandTotal
	}
	return 0
}

func (m *SuccessOrder) GetProgress() string {
	if m != nil {
		return m.Progress
	}
	return ""
}

func (m *SuccessOrder) GetTrackDetails() string {
	if m != nil {
		return m.TrackDetails
	}
	return ""
}

type PayResponse struct {
	Order                *Order        `protobuf:"bytes,1,opt,name=Order,proto3" json:"Order,omitempty"`
	Success              bool          `protobuf:"varint,2,opt,name=Success,proto3" json:"Success,omitempty"`
	SuccessOrder         *SuccessOrder `protobuf:"bytes,3,opt,name=SuccessOrder,proto3" json:"SuccessOrder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PayResponse) Reset()         { *m = PayResponse{} }
func (m *PayResponse) String() string { return proto.CompactTextString(m) }
func (*PayResponse) ProtoMessage()    {}
func (*PayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e51e679f9ae460e2, []int{27}
}

func (m *PayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PayResponse.Unmarshal(m, b)
}
func (m *PayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PayResponse.Marshal(b, m, deterministic)
}
func (m *PayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PayResponse.Merge(m, src)
}
func (m *PayResponse) XXX_Size() int {
	return xxx_messageInfo_PayResponse.Size(m)
}
func (m *PayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PayResponse proto.InternalMessageInfo

func (m *PayResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *PayResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *PayResponse) GetSuccessOrder() *SuccessOrder {
	if m != nil {
		return m.SuccessOrder
	}
	return nil
}

func init() {
	proto.RegisterType((*Category)(nil), "service.Category")
	proto.RegisterType((*VariantProduct)(nil), "service.VariantProduct")
	proto.RegisterType((*Product)(nil), "service.Product")
	proto.RegisterType((*Cart)(nil), "service.Cart")
	proto.RegisterType((*Order)(nil), "service.Order")
	proto.RegisterType((*LoginDetails)(nil), "service.LoginDetails")
	proto.RegisterType((*User)(nil), "service.User")
	proto.RegisterType((*SignupRequest)(nil), "service.SignupRequest")
	proto.RegisterType((*SignupResponse)(nil), "service.SignupResponse")
	proto.RegisterType((*LoginRequest)(nil), "service.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "service.LoginResponse")
	proto.RegisterType((*LogoutRequest)(nil), "service.LogoutRequest")
	proto.RegisterType((*LogoutResponse)(nil), "service.LogoutResponse")
	proto.RegisterType((*AddToCartRequest)(nil), "service.AddToCartRequest")
	proto.RegisterType((*AddToCartResponse)(nil), "service.AddToCartResponse")
	proto.RegisterType((*ReadCartRequest)(nil), "service.ReadCartRequest")
	proto.RegisterType((*ReadCartResponse)(nil), "service.ReadCartResponse")
	proto.RegisterType((*UpdateCartRequest)(nil), "service.UpdateCartRequest")
	proto.RegisterType((*UpdateCartResponse)(nil), "service.UpdateCartResponse")
	proto.RegisterType((*EmptyCartRequest)(nil), "service.EmptyCartRequest")
	proto.RegisterType((*EmptyCartResponse)(nil), "service.EmptyCartResponse")
	proto.RegisterType((*CheckoutRequest)(nil), "service.CheckoutRequest")
	proto.RegisterType((*CheckoutResponse)(nil), "service.CheckoutResponse")
	proto.RegisterType((*EditUserRequest)(nil), "service.EditUserRequest")
	proto.RegisterType((*EditUserResponse)(nil), "service.EditUserResponse")
	proto.RegisterType((*PayRequest)(nil), "service.PayRequest")
	proto.RegisterType((*SuccessOrder)(nil), "service.SuccessOrder")
	proto.RegisterType((*PayResponse)(nil), "service.PayResponse")
}

func init() { proto.RegisterFile("service/service.proto", fileDescriptor_e51e679f9ae460e2) }

var fileDescriptor_e51e679f9ae460e2 = []byte{
	// 1212 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0x6d, 0x6f, 0xe3, 0xc4,
	0x13, 0x97, 0xf3, 0x54, 0x7b, 0xd2, 0xa6, 0xc9, 0xfe, 0x7b, 0x3d, 0x5f, 0xfe, 0x08, 0x05, 0x0b,
	0xa1, 0xea, 0xa0, 0x77, 0x5c, 0x0e, 0x0e, 0x15, 0x09, 0x55, 0xbd, 0x3e, 0xa0, 0x8a, 0x96, 0x33,
	0xdb, 0x96, 0xf7, 0x5b, 0x7b, 0x2f, 0xb1, 0xda, 0xd8, 0x61, 0xbd, 0xb9, 0x23, 0x2f, 0x78, 0x89,
	0xc4, 0x77, 0xe2, 0xfb, 0x20, 0xf1, 0x21, 0x4e, 0x42, 0xbb, 0x5e, 0xaf, 0x37, 0x76, 0x4a, 0x8a,
	0x74, 0x12, 0xbc, 0x6a, 0xe6, 0x69, 0x67, 0xe6, 0x37, 0xe3, 0xdf, 0xa8, 0xf0, 0x20, 0xa5, 0xec,
	0x4d, 0x14, 0xd0, 0xa7, 0xea, 0xef, 0x93, 0x29, 0x4b, 0x78, 0x82, 0xd6, 0x94, 0xe8, 0xfd, 0x6e,
	0x81, 0x7d, 0x48, 0x38, 0x1d, 0x25, 0x6c, 0x8e, 0x10, 0x34, 0xbe, 0x27, 0x13, 0xea, 0x5a, 0x03,
	0x6b, 0xc7, 0xc1, 0xf2, 0x37, 0xea, 0x40, 0xed, 0xf4, 0xc8, 0xad, 0x0d, 0xac, 0x9d, 0x26, 0xae,
	0x9d, 0x1e, 0xa1, 0x6f, 0xa0, 0xeb, 0x13, 0x46, 0x63, 0xae, 0xa2, 0x22, 0x9a, 0xba, 0xf5, 0x41,
	0x7d, 0xa7, 0x3d, 0xec, 0x3d, 0xc9, 0x73, 0xe4, 0x0f, 0xe2, 0x8a, 0x2b, 0xfa, 0x10, 0xe0, 0x74,
	0x42, 0x46, 0xd4, 0x27, 0x7c, 0x9c, 0xba, 0x8d, 0x41, 0x7d, 0xc7, 0xc1, 0x86, 0x06, 0x7d, 0x06,
	0xb6, 0xcf, 0x92, 0x70, 0x16, 0xf0, 0xd4, 0x6d, 0xca, 0x67, 0xbb, 0xfa, 0x59, 0x65, 0xc0, 0xda,
	0xc3, 0xfb, 0xb5, 0x06, 0x9d, 0x1f, 0x09, 0x8b, 0x48, 0xcc, 0x95, 0x6e, 0x69, 0x0f, 0xbb, 0x45,
	0x8f, 0xb2, 0x93, 0xa5, 0xb5, 0x16, 0x30, 0x64, 0x2d, 0xd7, 0x75, 0xcb, 0xab, 0x6a, 0xfe, 0x00,
	0x9c, 0xab, 0x38, 0xe2, 0x3e, 0x8b, 0x02, 0xea, 0x36, 0x65, 0x58, 0xa1, 0x40, 0x5d, 0xa8, 0x9f,
	0x63, 0xdf, 0x6d, 0x49, 0xbd, 0xf8, 0x89, 0xfa, 0xa2, 0x9c, 0x74, 0x7c, 0x4d, 0x82, 0x1b, 0x77,
	0x4d, 0xaa, 0xb5, 0x2c, 0xca, 0x17, 0xa1, 0xae, 0x9d, 0x95, 0x2f, 0x7e, 0xa3, 0x01, 0xb4, 0xcf,
	0xe9, 0xe4, 0x9a, 0xb2, 0x2c, 0x83, 0x23, 0x43, 0x4c, 0x95, 0x87, 0x61, 0xed, 0xef, 0xfa, 0x7f,
	0x0e, 0xb6, 0x42, 0x29, 0x75, 0x6b, 0x12, 0xd4, 0x87, 0xba, 0xff, 0x45, 0xf8, 0xb0, 0x76, 0xf4,
	0xde, 0x42, 0xe3, 0x90, 0x30, 0x2e, 0x82, 0xf5, 0x44, 0xac, 0x15, 0xc1, 0xb9, 0xa3, 0x80, 0xec,
	0x87, 0x19, 0x89, 0x79, 0xc4, 0xc5, 0x7e, 0x88, 0x9c, 0x4d, 0x6c, 0x68, 0x24, 0x04, 0xc9, 0x64,
	0x42, 0x45, 0x45, 0x75, 0x09, 0xa8, 0x96, 0xbd, 0x77, 0x16, 0x34, 0x5f, 0xb1, 0x90, 0x32, 0xf4,
	0x51, 0x56, 0x82, 0xec, 0xa5, 0x3d, 0xdc, 0x30, 0x66, 0xc6, 0x38, 0xce, 0xaa, 0xf3, 0x60, 0xfd,
	0x24, 0x8a, 0xc9, 0xad, 0x8a, 0x96, 0xe3, 0x75, 0xf0, 0x82, 0x0e, 0x3d, 0x86, 0xee, 0x11, 0xbd,
	0x8d, 0xde, 0x50, 0x36, 0xbf, 0x8c, 0x26, 0xf4, 0x2a, 0x8e, 0x7e, 0x96, 0xd3, 0xad, 0xe3, 0x8a,
	0x1e, 0x3d, 0x85, 0xf6, 0x55, 0x4a, 0xd9, 0x11, 0xe5, 0x24, 0xba, 0x4d, 0xe5, 0x34, 0xcd, 0xcc,
	0xc2, 0x86, 0x4d, 0x0f, 0xb4, 0x05, 0xcd, 0xcb, 0x84, 0x93, 0x5b, 0x35, 0xe0, 0x4c, 0x10, 0xfd,
	0x5d, 0x8c, 0xa3, 0xe9, 0x34, 0x8a, 0x47, 0xf9, 0x88, 0x73, 0x59, 0x60, 0xf3, 0x2d, 0x23, 0x71,
	0x98, 0x85, 0xd9, 0xd2, 0x6a, 0x68, 0xbc, 0xaf, 0x61, 0xfd, 0x2c, 0x19, 0x45, 0x71, 0x9e, 0xa1,
	0x0f, 0xb6, 0x2e, 0xdb, 0x92, 0x65, 0x6b, 0x59, 0xae, 0xaa, 0xaf, 0x9a, 0xae, 0x9d, 0xfa, 0xde,
	0x9f, 0x75, 0x68, 0x88, 0xea, 0xc4, 0x4e, 0x9e, 0x44, 0x2c, 0xe5, 0xc6, 0x2e, 0x14, 0x0a, 0xf1,
	0xe4, 0x19, 0x51, 0xc6, 0x2c, 0x58, 0xcb, 0xa2, 0x21, 0x7f, 0x9c, 0xc4, 0x54, 0x41, 0x94, 0x09,
	0x42, 0x7b, 0x3c, 0x21, 0xd1, 0xad, 0xdb, 0x90, 0xee, 0x99, 0x20, 0xde, 0x39, 0x08, 0x43, 0x46,
	0xd3, 0xf4, 0x99, 0x84, 0xca, 0xc1, 0x5a, 0x36, 0x6c, 0x43, 0x89, 0x4d, 0x61, 0x1b, 0x8a, 0x25,
	0x3d, 0x8c, 0xf8, 0x5c, 0x42, 0xe3, 0x60, 0xf9, 0x5b, 0x64, 0xb8, 0xe0, 0x84, 0x53, 0xb5, 0xfa,
	0x99, 0x80, 0x5c, 0x58, 0x3b, 0x4c, 0x66, 0x31, 0x67, 0x73, 0xb9, 0xf7, 0x0e, 0xce, 0x45, 0x61,
	0xf1, 0xa3, 0x38, 0x48, 0x42, 0xea, 0x82, 0xac, 0x34, 0x17, 0xf5, 0xda, 0xb4, 0xef, 0x5e, 0x9b,
	0x2d, 0x68, 0x9e, 0xcc, 0xe2, 0x30, 0x75, 0xd7, 0xb3, 0xa9, 0x49, 0x01, 0x6d, 0x43, 0x2b, 0xfb,
	0xaa, 0xdc, 0x8d, 0x81, 0xb5, 0x63, 0x63, 0x25, 0xa1, 0xbd, 0xc5, 0x89, 0xb8, 0x1d, 0xf9, 0x19,
	0x3c, 0xd0, 0x0f, 0x9b, 0x46, 0x5c, 0x19, 0x9e, 0x4f, 0xd2, 0xf4, 0x6d, 0xc2, 0x42, 0x77, 0x33,
	0x43, 0x21, 0x97, 0xd1, 0x2e, 0xb4, 0xe4, 0x9e, 0xa7, 0x6e, 0xb7, 0xf4, 0xe0, 0xc5, 0x2c, 0x08,
	0x68, 0x9a, 0x4a, 0x2b, 0x56, 0x4e, 0x8a, 0x96, 0x7a, 0x6a, 0xd6, 0x47, 0xde, 0x10, 0x36, 0x2e,
	0xa2, 0x51, 0x3c, 0x9b, 0x62, 0xfa, 0xd3, 0x8c, 0xa6, 0x5c, 0xf4, 0x2d, 0x66, 0x5f, 0xf9, 0x5c,
	0xe4, 0xd2, 0x4a, 0x93, 0x77, 0x0e, 0x9d, 0x3c, 0x26, 0x9d, 0x26, 0x71, 0x4a, 0xef, 0x11, 0x24,
	0x90, 0x56, 0x05, 0xc9, 0x65, 0xb1, 0x71, 0x2e, 0x7a, 0x63, 0x05, 0x4c, 0x5e, 0x81, 0xde, 0x12,
	0xab, 0xb4, 0x25, 0x1a, 0x83, 0x5a, 0x09, 0x83, 0x4f, 0xa0, 0x73, 0x99, 0x7c, 0x47, 0xe9, 0xf4,
	0x2c, 0x19, 0x8d, 0x68, 0x78, 0x1a, 0xcb, 0xb5, 0xb3, 0x71, 0x49, 0x2b, 0x9a, 0x55, 0x99, 0xee,
	0x5d, 0xb7, 0x8a, 0x49, 0x66, 0xfc, 0x1f, 0x00, 0xf4, 0x18, 0x3a, 0x79, 0x8c, 0x4a, 0x64, 0x74,
	0x6f, 0x2d, 0x76, 0xff, 0x0b, 0x74, 0x0f, 0xc2, 0xf0, 0x32, 0x91, 0x7b, 0xa5, 0x52, 0x3c, 0xd3,
	0x4c, 0xac, 0xb2, 0xdc, 0x49, 0x96, 0x9a, 0xb1, 0xfb, 0x60, 0x2b, 0x66, 0x9c, 0xab, 0x3b, 0xab,
	0xe5, 0x12, 0x4f, 0x5a, 0x0b, 0x3c, 0xb9, 0x0b, 0x3d, 0x23, 0xfd, 0xca, 0x6a, 0x7b, 0xb0, 0x89,
	0x29, 0x09, 0x8d, 0x62, 0xbd, 0x2f, 0xa1, 0x5b, 0xa8, 0x0a, 0x5c, 0x57, 0x70, 0xae, 0xf7, 0x02,
	0x7a, 0x57, 0xd3, 0x90, 0x70, 0x6a, 0x36, 0x7e, 0x8f, 0xb8, 0xaf, 0x00, 0x99, 0x71, 0xa5, 0x84,
	0xb5, 0xbb, 0x03, 0x11, 0x74, 0x8f, 0x27, 0x53, 0x3e, 0x37, 0x6b, 0xdf, 0x85, 0x9e, 0xa1, 0x5b,
	0xd9, 0xfd, 0x17, 0xb0, 0x79, 0x38, 0xa6, 0xc1, 0xcd, 0xe2, 0x36, 0xac, 0xaa, 0x18, 0x43, 0xb7,
	0x88, 0x52, 0x39, 0x3e, 0x56, 0xd7, 0x49, 0xc5, 0x75, 0x74, 0x5c, 0xf6, 0xb5, 0xaa, 0xd3, 0x75,
	0xf7, 0x37, 0x33, 0x81, 0xcd, 0xe3, 0x30, 0xe2, 0x72, 0xe7, 0x54, 0x25, 0xbb, 0x00, 0x42, 0x7c,
	0x49, 0x5f, 0x27, 0x8c, 0x2e, 0xdf, 0x4e, 0xc3, 0x01, 0x7d, 0x0a, 0x8e, 0x90, 0x0e, 0x5e, 0x73,
	0xca, 0x2a, 0xb0, 0x49, 0xef, 0xc2, 0xee, 0xbd, 0x82, 0x6e, 0x91, 0xee, 0x7d, 0x7c, 0xf3, 0x43,
	0x00, 0x9f, 0xcc, 0xf3, 0xd2, 0xef, 0x85, 0x86, 0xf7, 0x47, 0x0d, 0xd6, 0x4d, 0x4e, 0xfb, 0x37,
	0x2e, 0xfb, 0x00, 0xda, 0x3e, 0x99, 0x8b, 0xb0, 0x73, 0x71, 0x33, 0xb2, 0x3b, 0x66, 0xaa, 0xfe,
	0x03, 0xb7, 0x5f, 0x52, 0x25, 0x4b, 0x46, 0xe2, 0x4a, 0xaa, 0x7b, 0xa7, 0x65, 0x01, 0xc8, 0x25,
	0x23, 0xc1, 0x4d, 0x5e, 0x1f, 0x64, 0x80, 0x98, 0x3a, 0xef, 0x37, 0x4b, 0x76, 0xf9, 0xbe, 0x96,
	0x55, 0x5c, 0x3e, 0x73, 0x6e, 0x12, 0xdc, 0x3b, 0x0f, 0xd5, 0x82, 0xeb, 0xf0, 0x5d, 0x03, 0x9c,
	0xe3, 0x40, 0x0c, 0x8a, 0x05, 0x14, 0xed, 0x41, 0x2b, 0x3b, 0x3c, 0x68, 0xbb, 0x08, 0x36, 0xaf,
	0x57, 0xff, 0x61, 0x45, 0xaf, 0x7a, 0x78, 0x01, 0x4d, 0x49, 0xfd, 0xa8, 0x74, 0x70, 0xf3, 0xc0,
	0xed, 0xb2, 0x5a, 0xc5, 0xed, 0x41, 0x2b, 0xa3, 0x72, 0xb4, 0xe0, 0x51, 0x30, 0x80, 0x91, 0xb2,
	0xc4, 0xf9, 0x2f, 0xc1, 0xd1, 0xd4, 0x8a, 0x1e, 0x69, 0xaf, 0x32, 0xdb, 0xf7, 0xfb, 0xcb, 0x4c,
	0xea, 0x8d, 0x7d, 0xb0, 0x73, 0x72, 0x45, 0xae, 0xf6, 0x2b, 0x51, 0x70, 0xff, 0xd1, 0x12, 0x8b,
	0x7a, 0xe0, 0x18, 0xa0, 0xa0, 0x4b, 0x54, 0xa4, 0xaa, 0x70, 0x6f, 0xff, 0xff, 0x4b, 0x6d, 0x45,
	0x2f, 0x9a, 0x28, 0x8d, 0x5e, 0xca, 0x84, 0x6a, 0xf4, 0x52, 0xe5, 0xd5, 0x7d, 0xb0, 0x73, 0x1e,
	0x34, 0x7a, 0x29, 0x11, 0xaa, 0xd1, 0x4b, 0x85, 0x34, 0xf7, 0xc1, 0xce, 0x59, 0xc8, 0x78, 0xa0,
	0xc4, 0x83, 0xc6, 0x03, 0x15, 0xca, 0xfa, 0x1c, 0xea, 0x3e, 0x99, 0xa3, 0xff, 0x15, 0xff, 0x0c,
	0x6a, 0x0e, 0xea, 0x6f, 0x2d, 0x2a, 0xb3, 0x88, 0xeb, 0x96, 0xfc, 0x4f, 0xf7, 0xf9, 0x5f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x27, 0x21, 0x4a, 0xfa, 0x02, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EcommerceClient is the client API for Ecommerce service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EcommerceClient interface {
	Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error)
	AddToCart(ctx context.Context, in *AddToCartRequest, opts ...grpc.CallOption) (*AddToCartResponse, error)
	ReadCart(ctx context.Context, in *ReadCartRequest, opts ...grpc.CallOption) (*ReadCartResponse, error)
	UpdateCart(ctx context.Context, in *UpdateCartRequest, opts ...grpc.CallOption) (*UpdateCartResponse, error)
	EmptyCart(ctx context.Context, in *EmptyCartRequest, opts ...grpc.CallOption) (*EmptyCartResponse, error)
	Checkout(ctx context.Context, in *CheckoutRequest, opts ...grpc.CallOption) (*CheckoutResponse, error)
	EditUser(ctx context.Context, in *EditUserRequest, opts ...grpc.CallOption) (*EditUserResponse, error)
	Pay(ctx context.Context, in *PayRequest, opts ...grpc.CallOption) (*PayResponse, error)
}

type ecommerceClient struct {
	cc *grpc.ClientConn
}

func NewEcommerceClient(cc *grpc.ClientConn) EcommerceClient {
	return &ecommerceClient{cc}
}

func (c *ecommerceClient) Signup(ctx context.Context, in *SignupRequest, opts ...grpc.CallOption) (*SignupResponse, error) {
	out := new(SignupResponse)
	err := c.cc.Invoke(ctx, "/service.Ecommerce/Signup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/service.Ecommerce/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceClient) Logout(ctx context.Context, in *LogoutRequest, opts ...grpc.CallOption) (*LogoutResponse, error) {
	out := new(LogoutResponse)
	err := c.cc.Invoke(ctx, "/service.Ecommerce/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceClient) AddToCart(ctx context.Context, in *AddToCartRequest, opts ...grpc.CallOption) (*AddToCartResponse, error) {
	out := new(AddToCartResponse)
	err := c.cc.Invoke(ctx, "/service.Ecommerce/AddToCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceClient) ReadCart(ctx context.Context, in *ReadCartRequest, opts ...grpc.CallOption) (*ReadCartResponse, error) {
	out := new(ReadCartResponse)
	err := c.cc.Invoke(ctx, "/service.Ecommerce/ReadCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceClient) UpdateCart(ctx context.Context, in *UpdateCartRequest, opts ...grpc.CallOption) (*UpdateCartResponse, error) {
	out := new(UpdateCartResponse)
	err := c.cc.Invoke(ctx, "/service.Ecommerce/UpdateCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceClient) EmptyCart(ctx context.Context, in *EmptyCartRequest, opts ...grpc.CallOption) (*EmptyCartResponse, error) {
	out := new(EmptyCartResponse)
	err := c.cc.Invoke(ctx, "/service.Ecommerce/EmptyCart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceClient) Checkout(ctx context.Context, in *CheckoutRequest, opts ...grpc.CallOption) (*CheckoutResponse, error) {
	out := new(CheckoutResponse)
	err := c.cc.Invoke(ctx, "/service.Ecommerce/Checkout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceClient) EditUser(ctx context.Context, in *EditUserRequest, opts ...grpc.CallOption) (*EditUserResponse, error) {
	out := new(EditUserResponse)
	err := c.cc.Invoke(ctx, "/service.Ecommerce/EditUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ecommerceClient) Pay(ctx context.Context, in *PayRequest, opts ...grpc.CallOption) (*PayResponse, error) {
	out := new(PayResponse)
	err := c.cc.Invoke(ctx, "/service.Ecommerce/Pay", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EcommerceServer is the server API for Ecommerce service.
type EcommerceServer interface {
	Signup(context.Context, *SignupRequest) (*SignupResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Logout(context.Context, *LogoutRequest) (*LogoutResponse, error)
	AddToCart(context.Context, *AddToCartRequest) (*AddToCartResponse, error)
	ReadCart(context.Context, *ReadCartRequest) (*ReadCartResponse, error)
	UpdateCart(context.Context, *UpdateCartRequest) (*UpdateCartResponse, error)
	EmptyCart(context.Context, *EmptyCartRequest) (*EmptyCartResponse, error)
	Checkout(context.Context, *CheckoutRequest) (*CheckoutResponse, error)
	EditUser(context.Context, *EditUserRequest) (*EditUserResponse, error)
	Pay(context.Context, *PayRequest) (*PayResponse, error)
}

// UnimplementedEcommerceServer can be embedded to have forward compatible implementations.
type UnimplementedEcommerceServer struct {
}

func (*UnimplementedEcommerceServer) Signup(ctx context.Context, req *SignupRequest) (*SignupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Signup not implemented")
}
func (*UnimplementedEcommerceServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedEcommerceServer) Logout(ctx context.Context, req *LogoutRequest) (*LogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (*UnimplementedEcommerceServer) AddToCart(ctx context.Context, req *AddToCartRequest) (*AddToCartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToCart not implemented")
}
func (*UnimplementedEcommerceServer) ReadCart(ctx context.Context, req *ReadCartRequest) (*ReadCartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadCart not implemented")
}
func (*UnimplementedEcommerceServer) UpdateCart(ctx context.Context, req *UpdateCartRequest) (*UpdateCartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCart not implemented")
}
func (*UnimplementedEcommerceServer) EmptyCart(ctx context.Context, req *EmptyCartRequest) (*EmptyCartResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmptyCart not implemented")
}
func (*UnimplementedEcommerceServer) Checkout(ctx context.Context, req *CheckoutRequest) (*CheckoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Checkout not implemented")
}
func (*UnimplementedEcommerceServer) EditUser(ctx context.Context, req *EditUserRequest) (*EditUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditUser not implemented")
}
func (*UnimplementedEcommerceServer) Pay(ctx context.Context, req *PayRequest) (*PayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pay not implemented")
}

func RegisterEcommerceServer(s *grpc.Server, srv EcommerceServer) {
	s.RegisterService(&_Ecommerce_serviceDesc, srv)
}

func _Ecommerce_Signup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServer).Signup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Ecommerce/Signup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServer).Signup(ctx, req.(*SignupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ecommerce_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Ecommerce/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ecommerce_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Ecommerce/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServer).Logout(ctx, req.(*LogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ecommerce_AddToCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddToCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServer).AddToCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Ecommerce/AddToCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServer).AddToCart(ctx, req.(*AddToCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ecommerce_ReadCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServer).ReadCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Ecommerce/ReadCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServer).ReadCart(ctx, req.(*ReadCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ecommerce_UpdateCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServer).UpdateCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Ecommerce/UpdateCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServer).UpdateCart(ctx, req.(*UpdateCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ecommerce_EmptyCart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyCartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServer).EmptyCart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Ecommerce/EmptyCart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServer).EmptyCart(ctx, req.(*EmptyCartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ecommerce_Checkout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServer).Checkout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Ecommerce/Checkout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServer).Checkout(ctx, req.(*CheckoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ecommerce_EditUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServer).EditUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Ecommerce/EditUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServer).EditUser(ctx, req.(*EditUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ecommerce_Pay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EcommerceServer).Pay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Ecommerce/Pay",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EcommerceServer).Pay(ctx, req.(*PayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ecommerce_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Ecommerce",
	HandlerType: (*EcommerceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Signup",
			Handler:    _Ecommerce_Signup_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _Ecommerce_Login_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Ecommerce_Logout_Handler,
		},
		{
			MethodName: "AddToCart",
			Handler:    _Ecommerce_AddToCart_Handler,
		},
		{
			MethodName: "ReadCart",
			Handler:    _Ecommerce_ReadCart_Handler,
		},
		{
			MethodName: "UpdateCart",
			Handler:    _Ecommerce_UpdateCart_Handler,
		},
		{
			MethodName: "EmptyCart",
			Handler:    _Ecommerce_EmptyCart_Handler,
		},
		{
			MethodName: "Checkout",
			Handler:    _Ecommerce_Checkout_Handler,
		},
		{
			MethodName: "EditUser",
			Handler:    _Ecommerce_EditUser_Handler,
		},
		{
			MethodName: "Pay",
			Handler:    _Ecommerce_Pay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/service.proto",
}
